services:
  db:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_DB: plf 
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - plf_data:/var/lib/postgresql/data

volumes:
  plf_data: