from probabilistic_load_forecast.infrastructure.entsoe.mapper import XML_Load_Mapper
from probabilistic_load_forecast.domain.entities import Measurement


SAMPLE_XML = """<?xml version="1.0" encoding="UTF-8"?>
<GL_MarketDocument xmlns="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0">
    <mRID>d000ad80516d4af69ee19cdd7e947b8c</mRID>
    <revisionNumber>1</revisionNumber>
    <type>A65</type>
    <process.processType>A16</process.processType>
    <sender_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</sender_MarketParticipant.mRID>
    <sender_MarketParticipant.marketRole.type>A32</sender_MarketParticipant.marketRole.type>
    <receiver_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</receiver_MarketParticipant.mRID>
    <receiver_MarketParticipant.marketRole.type>A33</receiver_MarketParticipant.marketRole.type>
    <createdDateTime>2025-07-15T10:01:08Z</createdDateTime>
    <time_Period.timeInterval>
        <start>2025-07-13T00:00Z</start>
        <end>2025-07-14T00:00Z</end>
    </time_Period.timeInterval>
    <TimeSeries>
        <mRID>1</mRID>
        <businessType>A04</businessType>
        <objectAggregation>A01</objectAggregation>
        <outBiddingZone_Domain.mRID codingScheme="A01">10YAT-APG------L</outBiddingZone_Domain.mRID>
        <quantity_Measure_Unit.name>MAW</quantity_Measure_Unit.name>
        <curveType>A01</curveType>
        <Period>
            <timeInterval>
                <start>2025-07-13T00:00Z</start>
                <end>2025-07-14T00:00Z</end>
            </timeInterval>
            <resolution>PT15M</resolution>
            <Point>
                <position>1</position>
                <quantity>4544</quantity>
            </Point>
            <Point>
                <position>2</position>
                <quantity>4529</quantity>
            </Point>
            <Point>
                <position>3</position>
                <quantity>4460</quantity>
            </Point>
            <Point>
                <position>4</position>
                <quantity>4416</quantity>
            </Point>
            <Point>
                <position>5</position>
                <quantity>4369</quantity>
            </Point>
            <Point>
                <position>6</position>
                <quantity>4341</quantity>
            </Point>
            <Point>
                <position>7</position>
                <quantity>4342</quantity>
            </Point>
            <Point>
                <position>8</position>
                <quantity>4338</quantity>
            </Point>
            <Point>
                <position>9</position>
                <quantity>4331</quantity>
            </Point>
            <Point>
                <position>10</position>
                <quantity>4341</quantity>
            </Point>
            <Point>
                <position>11</position>
                <quantity>4326</quantity>
            </Point>
            <Point>
                <position>12</position>
                <quantity>4334</quantity>
            </Point>
            <Point>
                <position>13</position>
                <quantity>4365</quantity>
            </Point>
            <Point>
                <position>14</position>
                <quantity>4379</quantity>
            </Point>
            <Point>
                <position>15</position>
                <quantity>4386</quantity>
            </Point>
            <Point>
                <position>16</position>
                <quantity>4412</quantity>
            </Point>
            <Point>
                <position>17</position>
                <quantity>4430</quantity>
            </Point>
            <Point>
                <position>18</position>
                <quantity>4495</quantity>
            </Point>
            <Point>
                <position>19</position>
                <quantity>4543</quantity>
            </Point>
            <Point>
                <position>20</position>
                <quantity>4579</quantity>
            </Point>
            <Point>
                <position>21</position>
                <quantity>4573</quantity>
            </Point>
            <Point>
                <position>22</position>
                <quantity>4562</quantity>
            </Point>
            <Point>
                <position>23</position>
                <quantity>4549</quantity>
            </Point>
            <Point>
                <position>24</position>
                <quantity>4661</quantity>
            </Point>
            <Point>
                <position>25</position>
                <quantity>4708</quantity>
            </Point>
            <Point>
                <position>26</position>
                <quantity>4822</quantity>
            </Point>
            <Point>
                <position>27</position>
                <quantity>4876</quantity>
            </Point>
            <Point>
                <position>28</position>
                <quantity>4919</quantity>
            </Point>
            <Point>
                <position>29</position>
                <quantity>4928</quantity>
            </Point>
            <Point>
                <position>30</position>
                <quantity>4959</quantity>
            </Point>
            <Point>
                <position>31</position>
                <quantity>4958</quantity>
            </Point>
            <Point>
                <position>32</position>
                <quantity>4990</quantity>
            </Point>
            <Point>
                <position>33</position>
                <quantity>5060</quantity>
            </Point>
            <Point>
                <position>34</position>
                <quantity>5042</quantity>
            </Point>
            <Point>
                <position>35</position>
                <quantity>5074</quantity>
            </Point>
            <Point>
                <position>36</position>
                <quantity>5083</quantity>
            </Point>
            <Point>
                <position>37</position>
                <quantity>5114</quantity>
            </Point>
            <Point>
                <position>38</position>
                <quantity>5132</quantity>
            </Point>
            <Point>
                <position>39</position>
                <quantity>5156</quantity>
            </Point>
            <Point>
                <position>40</position>
                <quantity>5130</quantity>
            </Point>
            <Point>
                <position>41</position>
                <quantity>5003</quantity>
            </Point>
            <Point>
                <position>42</position>
                <quantity>4902</quantity>
            </Point>
            <Point>
                <position>43</position>
                <quantity>4798</quantity>
            </Point>
            <Point>
                <position>44</position>
                <quantity>4769</quantity>
            </Point>
            <Point>
                <position>45</position>
                <quantity>4731</quantity>
            </Point>
            <Point>
                <position>46</position>
                <quantity>4620</quantity>
            </Point>
            <Point>
                <position>47</position>
                <quantity>4538</quantity>
            </Point>
            <Point>
                <position>48</position>
                <quantity>4467</quantity>
            </Point>
            <Point>
                <position>49</position>
                <quantity>4483</quantity>
            </Point>
            <Point>
                <position>50</position>
                <quantity>4579</quantity>
            </Point>
            <Point>
                <position>51</position>
                <quantity>4662</quantity>
            </Point>
            <Point>
                <position>52</position>
                <quantity>4665</quantity>
            </Point>
            <Point>
                <position>53</position>
                <quantity>4638</quantity>
            </Point>
            <Point>
                <position>54</position>
                <quantity>4664</quantity>
            </Point>
            <Point>
                <position>55</position>
                <quantity>4736</quantity>
            </Point>
            <Point>
                <position>56</position>
                <quantity>4915</quantity>
            </Point>
            <Point>
                <position>57</position>
                <quantity>4953</quantity>
            </Point>
            <Point>
                <position>58</position>
                <quantity>5030</quantity>
            </Point>
            <Point>
                <position>59</position>
                <quantity>5034</quantity>
            </Point>
            <Point>
                <position>60</position>
                <quantity>5143</quantity>
            </Point>
            <Point>
                <position>61</position>
                <quantity>5021</quantity>
            </Point>
            <Point>
                <position>62</position>
                <quantity>5132</quantity>
            </Point>
            <Point>
                <position>63</position>
                <quantity>5174</quantity>
            </Point>
            <Point>
                <position>64</position>
                <quantity>5278</quantity>
            </Point>
            <Point>
                <position>65</position>
                <quantity>5335</quantity>
            </Point>
            <Point>
                <position>66</position>
                <quantity>5390</quantity>
            </Point>
            <Point>
                <position>67</position>
                <quantity>5495</quantity>
            </Point>
            <Point>
                <position>68</position>
                <quantity>5579</quantity>
            </Point>
            <Point>
                <position>69</position>
                <quantity>5650</quantity>
            </Point>
            <Point>
                <position>70</position>
                <quantity>5702</quantity>
            </Point>
            <Point>
                <position>71</position>
                <quantity>5732</quantity>
            </Point>
            <Point>
                <position>72</position>
                <quantity>5770</quantity>
            </Point>
            <Point>
                <position>73</position>
                <quantity>5821</quantity>
            </Point>
            <Point>
                <position>74</position>
                <quantity>5829</quantity>
            </Point>
            <Point>
                <position>75</position>
                <quantity>5802</quantity>
            </Point>
            <Point>
                <position>76</position>
                <quantity>5799</quantity>
            </Point>
            <Point>
                <position>77</position>
                <quantity>5713</quantity>
            </Point>
            <Point>
                <position>78</position>
                <quantity>5672</quantity>
            </Point>
            <Point>
                <position>79</position>
                <quantity>5605</quantity>
            </Point>
            <Point>
                <position>80</position>
                <quantity>5583</quantity>
            </Point>
            <Point>
                <position>81</position>
                <quantity>5698</quantity>
            </Point>
            <Point>
                <position>82</position>
                <quantity>5629</quantity>
            </Point>
            <Point>
                <position>83</position>
                <quantity>5502</quantity>
            </Point>
            <Point>
                <position>84</position>
                <quantity>5410</quantity>
            </Point>
            <Point>
                <position>85</position>
                <quantity>5344</quantity>
            </Point>
            <Point>
                <position>86</position>
                <quantity>5252</quantity>
            </Point>
            <Point>
                <position>87</position>
                <quantity>5152</quantity>
            </Point>
            <Point>
                <position>88</position>
                <quantity>5081</quantity>
            </Point>
            <Point>
                <position>89</position>
                <quantity>5282</quantity>
            </Point>
            <Point>
                <position>90</position>
                <quantity>5195</quantity>
            </Point>
            <Point>
                <position>91</position>
                <quantity>5089</quantity>
            </Point>
            <Point>
                <position>92</position>
                <quantity>5023</quantity>
            </Point>
            <Point>
                <position>93</position>
                <quantity>5000</quantity>
            </Point>
            <Point>
                <position>94</position>
                <quantity>4938</quantity>
            </Point>
            <Point>
                <position>95</position>
                <quantity>4881</quantity>
            </Point>
            <Point>
                <position>96</position>
                <quantity>4836</quantity>
            </Point>
        </Period>
    </TimeSeries>
</GL_MarketDocument>"""

def test_parse_xml_load_data():
    result = XML_Load_Mapper.map(SAMPLE_XML)
    assert isinstance(result, list)
    assert result[0] == Measurement(timestamp="2025-07-13T00:00:00+00:00", value=4544)
    assert result[1] == Measurement(timestamp="2025-07-13T00:15:00+00:00", value=4529)
